### ISSUE TITLE
can not use the model visualizer

### ISSUE THREAD

**Issue by mandolinable** [BriefFiniteElementNet/BriefFiniteElement.Net#14]
I am having problem with visualizer   
I am using this code to display viusalizer 

```
ModelVisualizerControl ctrlVisualizer = new ModelVisualizerControl();
            ctrlVisualizer.ModelToVisualize = model;
            ctrlVisualizer.ShowElements = true;
            //ctrlVisualizer.ElementVisualThickness = 0.02;
            ctrlVisualizer.ShowNodes = true;
            ctrlVisualizer.ShowRigidElements = true;
            ctrlVisualizer.ShowConstraints = true;
            ctrlVisualizer.ShowNodalLoads = true;
            ctrlVisualizer.ShowNodalLoads_Force = true;
            ctrlVisualizer.ShowElements = true;
            ctrlVisualizer.DisableEditingProperties = true;
            ctrlVisualizer.ShowConstraints = true;
```
the message is 
Could not load file or assembly 'HelixToolkit, Version=2011.7.1.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

source is "BriefFiniteElementNet.Controls"

and the satck trace 
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at BriefFiniteElementNet.Controls.ModelVisualizerControl.InitializeComponent()
   at BriefFiniteElementNet.Controls.ModelVisualizerControl..ctor()
   at WpfApp1.MainWindow.Button_Click(Object sender, RoutedEventArgs e) in C:\Users\a.maher\Desktop\BriefFiniteElement\Test\TestBriefFinite\WpfApp1\MainWindow.xaml.cs:line 302

and here is the references and packages 
![1](https://user-images.githubusercontent.com/46298386/50584456-536c9480-0e78-11e9-8adb-9179b3c57b85.png)
![2](https://user-images.githubusercontent.com/46298386/50584457-536c9480-0e78-11e9-9949-e36a3f87cdcc.png)

**Comment by epsi1on** [comment]
Hello,
I think it is because of nuget packages that are not included in git repo anymore and they need to be restored/downloaded.
Can you please try to build with option 'nuget package restore' enabled (like [this](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#enabling-and-disabling-package-restore))

Thanks

**Comment by epsi1on** [comment]
Code is updated,
can you please check again?
thanks
