### ISSUE TITLE
Various crashes Matrix functions

### ISSUE THREAD

**Issue by rubsy92** [BriefFiniteElementNet/BriefFiniteElement.Net#78]
**Describe the bug**

- Crash on "SetMember" in Matrix class when getting the internal force
- Crash on "mDkt" in GetLocalInternalStressAt in the DktHelper class

**To Reproduce**
Any triangular shell case

**Comment by epsi1on** [comment]
Could you please also put stack trace something of exception (I mean `Exception.StackTrace` property)
Thanks

**Comment by rubsy92** [comment]
E.g. for the SetMember-bug: 
Exception: Invallid column or row specified
StackTrace (reduced):
   at BriefFiniteElementNet.MatrixException.ThrowIf(Boolean condition, String message) in \BriefFiniteElementNet.Common\MatrixException.cs:line 48
   at BriefFiniteElementNet.Matrix.SetMember(Int32 row, Int32 column, Double value) in \BriefFiniteElementNet.Common\Matrix.cs:line 647
   at BriefFiniteElementNet.Matrix.set_TheMember(Int32 row, Int32 column, Double value) in \BriefFiniteElementNet.Common\Matrix.cs:line 453
   at BriefFiniteElementNet.Matrix.FillColumn(Int32 colNum, Double[] values) in \BriefFiniteElementNet.Common\Matrix.cs:line 1832
   at BriefFiniteElementNet.ElementHelpers.CstHelper.GetLocalInternalForce(Element targetElement, LoadCase loadCase, Double[] isoCoords) in \BriefFiniteElementNet\ElementHelpers\CstHelper.cs:line 284
   at SolverTest.Testcases.S3ShellTester.writeDataTriangleElement(Model model, LoadCase testCase) in Validation\Code\SolverTest\SolverTest\Testcases\S3ShellTester.cs:line 351
   at SolverTest.Testcases.S3ShellTester.Model1Test2() in Validation\Code\SolverTest\SolverTest\Testcases\S3ShellTester.cs:line 84
   at SolverTest.Form1.button2_Click(Object sender, EventArgs e) in Validation\Code\SolverTest\SolverTest\Form1.cs:line 38

**Comment by epsi1on** [comment]
Thanks for report, so it shows `CstHelper.GetLocalInternalForce()` throws exception. 
Will check it...

**Comment by epsi1on** [comment]
Seems error is gone for now, can you please do a check again?
Thanks
